# Title Here

An short introduction about PyTorch and about the chosen functions.

- function 1
- function 2
- function 3
- function 4
- function 5

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.tensor


In [ ]:
# Example 1 - working
#A tensor is a vector(1-d), matrix(2-d), and n-dimensional array.
data = torch.tensor([[1,2],
                     [3,4],
                     [5,6]])

Explanation about example

In [ ]:
# Example 2 - working
#Here we can just add the datatype of the tensor in the end while creating a tensor
float_tensor = torch.tensor([[23,22],
                             [33,45]],dtype=torch.float)
print(float_tensor)

#OR
#here we can convert the dataset into floating point number by adding just a decimal point to any number and the whole tensor dataset would get converted into
#floating point number
#float_tensor = torch.tensor([[23.,22],
#                             [33,45]])
#print(float_tensor)

tensor([[23., 22.],
        [33., 45.]])


Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
#Here in torch.tensors, if we making the tensors then it should be of same shape(dimensions),means the shape of array should be of same size, otherwise it
#will generate error
torch.tensor([[1],
              [3, 4.]])

ValueError: expected sequence of length 1 at dim 1 (got 2)

## Function 2 - torch.reshape


In [ ]:
# Example 1 - working
#torch.reshape changes the shape of a tensor without changing the data
x = torch.tensor([[1,2,3],
                 [4,5,6]])      #shape of tensor is 2x3
#reshaping tensor into 3x2, would not change the data itself
x.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
# Example 2 - working
y = torch.tensor([1,2,3,4,5,6])      #this is a 1-d tensor(a vector)

#reshaping y into 3x2
y.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
z = torch.tensor([1,2,3,4])  #this is a 1-d tensor which has 4 elements

#reshaping the tensor into 3x2, so it should have 6 elements but here we only have 4 elements so it will generate an error
z.reshape(3,2)

RuntimeError: shape '[3, 2]' is invalid for input of size 4

## Function 3 - torch.cat



In [ ]:
# Example 1 - working
#torch.cat is used to concatenate the two tensor into one and here we can give dimensions too.

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

#by using cat we will concatenate a & b with dim=0(dimension)
torch.cat((a,b), dim=0)
#dimension(dim=0), will convert th tensor into 4x2 shape

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
# Example 2 - working
#now we will concatenate the c & d tenors with dim=1
c = torch.tensor([[1,2],[2,3]])
d = torch.tensor([[3,4],[4,5]])

#by using dim=1(dimension), tensr would be converted into 2x4
torch.cat((c,d), dim=1)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
#now we'll concatenate the e & f tensor with dim-=0
e = torch.tensor([[1,2],[3,4]])
f = torch.tensor([5,6])

#here the shape of both the e & f don't align with each other, so we'll have an error concatenating the tensors, as they are of different shapes
torch.cat((e,f), dim=0)

RuntimeError: Tensors must have same number of dimensions: got 2 and 1

## Function 4 - torch.stack



In [ ]:
# Example 1 - working
#The torch.stck is used to add the two tensors same as cat(concatenate), but in a different way,
#the torch.cat, concatenate the tensors in the existing dimensions, whereas the stack add a new dimension, combining the tensors.

#creating  tensors
g = torch.tensor([[2,3],[4,5]])
h = torch.tensor([[4,5],[2,3]])
torch.stack((g,h), dim=0)

tensor([[[2, 3],
         [4, 5]],

        [[4, 5],
         [2, 3]]])

In [ ]:
# Example 2 - working
i = torch.tensor([1,2,4,3])
j = torch.tensor([5,7,8,9])
#stacking i & j along a new dimension, creating a 4x2 tensor
torch.stack((i,j), dim=1)

tensor([[1, 5],
        [2, 7],
        [4, 8],
        [3, 9]])

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
#the sizes of the tensors must be same to be stacked with eachother along a new dimension, otherwise it will generate an error
k = torch.tensor([2,3])
l = torch.tensor([4,5,6])
#the shapes of tensor must be same to be stacked
torch.stack((k,l), dim=0)

RuntimeError: stack expects each tensor to be equal size, but got [2] at entry 0 and [3] at entry 1

Explanation about example

## Function 5 - torch.mm



In [ ]:
# Example 1 - working
#torch.mm is used for matrix multiplication in pytorch

m = torch.tensor([[2,3],[4,5]])
n = torch.tensor([[6,7],[8,9]])

#performing matrix multiplication on two 2x2 tensors,
torch.mm(m,n)

so matrix multiplication will convert these two 2x2 tensors in one 2x2 tensor

tensor([[36, 41],
        [64, 73]])

In [ ]:
# Example 2 - working
o = torch.tensor([[1,2,3],[4,5,6]])  #2x3 tensor
p = torch.tensor([[7,8],[9,10],[11,12]])  #3x2 tensor

#performing matrix multiplication on two 2x3 & 3x2 tensors
torch.mm(o,p) #the result would be 2x2 tensor

tensor([[ 58,  64],
        [139, 154]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
#For matrix multiplication the matrix size/shape should be same, otherwise it will generate an error

q = torch.tensor([[1,2],[3,4]])
r = torch.tensor([[5,6]])

#performing matrix multiplication
torch.mm(q,r)    #will show error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2 and 1x2)


## Conclusion

Here we have worked on torch.tensors(is used to create a tensor), torch.cat(is used to concatenate two or more tensors), torch.reshape(is used to reshape teh tensors shape), torch.stack(is used to stack teh two or more tensors and creeate a new dimension), torch.mm(is used to perform the matrix multiplication on tensors). And here presented 2 working examples and one non-woring(error generating example).

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...